README update
szosk/web_system pull request #13
Opened 2020-04-07 14:44 UTC by mikgor

2020-04-07 16:15 UTC, kamilspringer commented on README.md
> +   npm run ng build
`npm run` is not needed here, all you need is `ng build --deploy-url static /`
`--deploy-url` is needed. It sets the path to `/static/...` in compiled .js files that reference other compiled .js files.

Translated by @NotJustPizza. Please keep all conversations in one language.

2020-04-07 16:16 UTC, kamilspringer approved these changes

2020-04-07 16:58 UTC, mikgor commented on README.md
> +   npm run ng build
Done

2020-04-08 19:32 UTC, NotJustPizza commented on README.md
> +   npm run ng build
`npm run` is required, without it we need to have `ng` in PATH

2020-04-08 19:34 UTC, NotJustPizza commented on README.md
> +   npm run ng build
Regarding `--deploy-url`, it's not working for me, but we probably don't need it all. 99.9% of time it will be set to `/static`, so why not use variable instead?

2020-04-08 19:39 UTC, NotJustPizza requested changes

2020-04-08 19:39 UTC, NotJustPizza commented on README.md
> +1. Change working directory to `szosk_system/main`.
Venv in `main` ? Not root project dir?

2020-04-08 19:39 UTC, NotJustPizza commented on README.md
> +   from django.core.management.utils import get_random_secret_key
It won't work without package, so we need to install `requirements.txt` first.

2020-04-08 19:39 UTC, NotJustPizza commented on README.md
> +### Collecting the static files into `STATIC_ROOT`
`STATIC_ROOT` (`szosk_system/static`)

2020-04-09 14:41 UTC, NotJustPizza approved these changes

2020-04-09 14:48 UTC, merged